version: '2.1'

services:
  db:
    image: mariadb:10.6.5
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: 'passwordpusher_user'
      MARIADB_PASSWORD: 'passwordpusher_passwd'
      MARIADB_DATABASE: 'passwordpusher_db'
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - /var/lib/pwpush-mysql/data:/var/lib/mysql

  pwpush:
    image: docker.io/pglombardo/pwpush-mysql:release
    ports:
      - "5100:5100"
    depends_on:
      - db
    links:
     - db:mysql
